apiVersion: v1
kind: PersistentVolume
metadata:
  name: mine-pv
spec:
  storageClassName: gluster-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/minecraft"